environment: production
chdir: /home/sinatra/tasket/current/
address: 127.0.0.1
user: sinatra
group: sinatra
port: 8000
pid: /home/sinatra/tasket/current/tmp/pids/thin.pid
rackup: /home/sinatra/tasket/current/config.ru
log: /home/sinatra/tasket/current/log/thin.log
max_conns: 1024
timeout: 30
max_persistent_conns: 512
daemonize: true